services:
  jitsi:
    image: docker.io/dbndev/jitsi:latest
    build:
      context: .
    container_name: jitsi-server
    privileged: true
    restart: unless-stopped
    environment:
      LOCAL_JITSI_CONTAINER_INSTALL: "true"
      LOCAL_DOCKER_JITSI_DIR: ${LOCAL_DOCKER_JITSI_DIR:-${PWD}/.containers}/docker-jitsi-meet
      CONTAINER_CACHE: ${CONTAINER_CACHE:-${PWD}/.containers/jitsi}
      JITSI_COMMIT: ${JITSI_COMMIT}
      JVB_PORT: "${JITSI_JVB_PORT}"
      HTTP_PORT: "${JITSI_HTTP_PORT}"
      HTTPS_PORT: "${JITSI_HTTPS_PORT}"
      JVB_ADVERTISE_IPS: ${JITSI_JVB_ADVERTISE_IPS}
      PUBLIC_URL: "${JITSI_URL:-https://${JITSI_DOMAIN}}"
      DOCKER_HOST: unix:///run/user/1000/docker.sock
      DOCKER_BUILDKIT: "1"
    ports:
      - "${JITSI_HTTP_PORT}:${JITSI_HTTP_PORT}/tcp"
      - "${JITSI_HTTPS_PORT}:${JITSI_HTTPS_PORT}/tcp"
      - "${JITSI_JVB_PORT}:${JITSI_JVB_PORT}/udp"
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - vscode-store:/vscode
    networks:
      stream:
        aliases:
          - jitsi
    extra_hosts:
      - "${JITSI_DOMAIN}:${JITSI_IP}"
    env_file:
      - ${ENV_FILE:-.env}

volumes:
  jitsi-cache:
  jitsi-docker:
  vscode-store:
    external: true
    name: vscode

networks:
  stream:
