services:
  jitsi:
    # restart: unless-stopped
    image: docker.io/dbndev/jitsi:latest
    build:
      context: .
    container_name: jitsi-server
    privileged: true
    environment:
      JITSI_DATA_DIR: ${JITSI_DATA_DIR:-${PWD}/.containers/jitsi}
      JITSI_CONFIG_DIR: ${JITSI_CONFIG_DIR:-${PWD}/.containers/jitsi/config}
      JITSI_COMMIT: ${JITSI_COMMIT}
      JVB_PORT: "${JITSI_JVB_PORT}"
      HTTP_PORT: "${JITSI_HTTP_PORT}"
      HTTPS_PORT: "${JITSI_HTTPS_PORT}"
      JVB_ADVERTISE_IPS: ${JITSI_JVB_ADVERTISE_IPS}
      PUBLIC_URL: "${JITSI_URL:-https://${JITSI_DOMAIN}}"
      DOCKER_HOST: unix:///run/user/1000/docker.sock
      DOCKER_BUILDKIT: "1"
    ports:
      - "${JITSI_HTTP_PORT}:${JITSI_HTTP_PORT}/tcp"
      - "${JITSI_HTTPS_PORT}:${JITSI_HTTPS_PORT}/tcp"
      - "${JITSI_JVB_PORT}:${JITSI_JVB_PORT}/udp"
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - vscode-store:/vscode
    extra_hosts:
      - "${JITSI_DOMAIN}:${JITSI_IP}"
    env_file:
      - ${ENV_FILE:-.env}
    dns:
      - ${VEGITO_DNS:-10.5.5.7}
    # entrypoint: bash
    # command: -c 'sleep infinity'
volumes:
  jitsi-cache:
  jitsi-docker:
  vscode-store:
    external: true
    name: vscode
